# Generated by Django 3.2.20 on 2023-08-19 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    replaces = [
        ('mail', '0001_initial'),
        ('mail', '0002_auto_20230731_2032'),
    ]

    dependencies = [
        ('django_email_accounts', '0001_initial_v2'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_key', models.CharField(max_length=40, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('commands', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserEmailBounceStats',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_email_accounts.useremail',),
        ),
        migrations.CreateModel(
            name='BounceStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mails_sent', models.IntegerField(default=0)),
                ('mails_bounced', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('user_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail.useremailbouncestats')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user_email', 'date')},
            },
        ),
    ]
