# Generated by Django 3.2.20 on 2023-08-19 16:25

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_email_accounts', '0001_initial_v2'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_email_accounts.user',),
        ),
    ]
